/**
 * Quick-and-Dirty class generated by macro that offers a small snippet of my killfeed as an array
 * I've removed my handle, so you can't all grief me, so I'm represented by "Me (21)" in the killer/victim properties
 * @author Kris
 *
 */
public class KillStream {
	
	public static void main(String[] args) {
		killDeathRatio();
		pandoraKills();
		peopleInOutit();
		victimLevels();
    }
	
	public static void peopleInOutit() {
		double kills = 0;

		for(int i = 0; i < KillStream.kills.length; i++) { 
			if(KillStream.kills[i].getKiller().equals("Me (21)") && KillStream.kills[i].getVictim().contains("[") && KillStream.kills[i].getVictim().contains("]")) {
				kills ++;
			}
		}
		
		System.out.println("People that killed in an outfit: " + kills);
	}
	
	public static void pandoraKills() {
		double kills = 0;
		
		for(int i = 0; i < KillStream.kills.length; i++) {
			if(KillStream.kills[i].getKiller().equals("Me (21)") && KillStream.kills[i].getWeapon().equals("Pandora VX25")) {
				kills ++;
			}
		}
		
		System.out.println("Pandora VX25 kills: " + kills);
	}
	
	public static void killDeathRatio() {

		double kills = 0;
		double deaths = 0;
		
		for(int i = 0; i < KillStream.kills.length; i++) {
			if(KillStream.kills[i].getKiller().equals("Me (21)")) {
				kills ++;
			} else {
				deaths ++;
			}
		}
		System.out.println("K/D ratio for session: " + (kills/deaths));
	}
	
	public static void victimLevels() {
		double lower = 0;
		double same = 0;
		double higher = 0;
		
		
		for(int i = 0; i < KillStream.kills.length; i++) {
			if(KillStream.kills[i].getVictim().equals("Me (21)")) {
				String[] victim = KillStream.kills[i].getVictim().split("\\((.*?)")[1].split("\\)");
				String _killer = KillStream.kills[i].getKiller();
				
				if(_killer.contains("(")) {

					String[] killerSplit = _killer.split("\\((.*?)")[1].split("\\)");

					if (killerSplit.length != 0) {

						int victimLevel = Integer.parseInt(killerSplit[0]);
						int killerLevel = Integer.parseInt(victim[0]);

						if(victimLevel < killerLevel) {
							lower ++;
						} else if(victimLevel > killerLevel) {
							higher ++;
						} else {
							same ++;
						}
					}
				}
			}
		}
		
		System.out.println("lower: " + lower);
		System.out.println("same: " + same);
		System.out.println("higher: " + higher);
		
	}
	
	
	//seriously, don't even look. This really is horrible.
	public static KillEvent[] kills = new KillEvent[] {
			new KillEvent("22/01/2023 21:04:12","Me (21)","[EPG] undo (9)","Lancer VS22"),
			new KillEvent("22/01/2023 21:04:12","Me (21)","[STN1] ArneEnra (97)","Lancer VS22"),
			new KillEvent("22/01/2023 21:04:12","Me (21)","[EPG] undo (9)","Lancer VS22"),
			new KillEvent("22/01/2023 21:00:50","[EPG] D1ps (15)","Me (21)","MG-C1 Kindred"),
			new KillEvent("22/01/2023 21:02:41","Sirolimus (19)","Me (21)","NS-11CB"),
			new KillEvent("22/01/2023 21:01:42","skrilrex (59)","Me (21)","NS-11C"),
			new KillEvent("22/01/2023 21:29:48","NighdaCobaltTR (9)","Me (21)","TS2 Inquisitor"),
			new KillEvent("22/01/2023 21:29:29","[EPG] sava7898 (65)","Me (21)","M20 Basilisk(Sunderer)"),
			new KillEvent("22/01/2023 21:25:18","Me (21)","[RBRN] CANKARLO (65)","NS-10 Burster"),
			new KillEvent("22/01/2023 21:16:59","[FGS1] dORet2Platine (9)","Me (21)","Breaker Rocket Pods(Reaver)"),
			new KillEvent("22/01/2023 21:15:55","Me (21)","[FGS1] dORet2Platine (9)","NS-10 Burster"),
			new KillEvent("22/01/2023 21:15:55","Me (21)","[FGS1] dORet2Platine (9)","NS-10 Burster"),
			new KillEvent("22/01/2023 21:12:10","Me (21)","[EPG] EntomaVuashirissa (28)","NS-10 Burster"),
			new KillEvent("22/01/2023 21:07:04","[RE4] lololfirefis12 (55)","Me (21)","Mag-Cutter"),
			new KillEvent("22/01/2023 20:47:21","brizekman (8)","Me (21)","GD-22S"),
			new KillEvent("22/01/2023 20:42:45","Vilgen (71)","Me (21)","NSX-P Naginata"),
			new KillEvent("22/01/2023 20:07:27","[RE4] Dimkom (64)","Me (21)","MGR-L1 Promise"),
			new KillEvent("22/01/2023 20:29:06","Me (21)","[BROS] Becketh (96)","Pandora VX25"),
			new KillEvent("22/01/2023 20:28:56","Me (21)","[BROS] NIKERIS (92)","Pandora VX25"),
			new KillEvent("22/01/2023 20:21:48","Me (21)","LOreXX ()","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:21:00","Me (21)","PinkFloofAI (18)","Flash"),
			new KillEvent("22/01/2023 20:21:00","Me (21)","LOreXX ()","Flash"),
			new KillEvent("22/01/2023 20:21:00","Arios1210 (4)","Me (21)","SG-100"),
			new KillEvent("22/01/2023 20:20:05","Me (21)","LOreXX ()","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:20:41","Me (21)","KurVestija (71)","Flash"),
			new KillEvent("22/01/2023 20:20:10","Me (21)","[HedP] Fresz1990 (4)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:20:09","Me (21)","Arios1210 (4)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:19:05","Me (21)","RobotHealer (2)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:19:05","Arios1210 (4)","Me (21)","SG-100"),
			new KillEvent("22/01/2023 20:19:09","[NCA7] FGGEEK (91)","Me (21)","NS Decimator"),
			new KillEvent("22/01/2023 20:19:00","[91AR] Samyybo (56)","Me (21)","Spitfire Auto-Turret(Spitfire Auto-Turret)"),
			new KillEvent("22/01/2023 20:19:00","Me (21)","[CRII] roubenz (7)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:18:52","Me (21)","[NCA7] FGGEEK (91)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:18:42","[NCA7] FGGEEK (91)","Me (21)","NS Decimator"),
			new KillEvent("22/01/2023 20:18:19","GevinDark (5)","Me (21)","AF-19 Mercenary"),
			new KillEvent("22/01/2023 20:18:18","Me (21)","[CRII] roubenz (7)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:18:18","Me (21)","HARDcoRE221 (99)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:18:08","Me (21)","[CRII] roubenz (7)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:17:02","[C0Q] maxlaminas (91)","Me (21)","M20 Basilisk(Sunderer)"),
			new KillEvent("22/01/2023 20:16:56","[C0Q] maxlaminas (91)","Me (21)","Tempest "),
			new KillEvent("22/01/2023 20:16:49","Me (21)","[C0Q] GoldSeiya (59)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 20:15:48","Arios1210 (4)","Me (21)","SG-100"),
			new KillEvent("22/01/2023 20:12:51","[91AP] OutWorldBlood (54)","Me (21)","The Moonshot"),
			new KillEvent("22/01/2023 20:12:11","[G6TR] L1mwaX (9)","Me (21)","GD-22S"),
			new KillEvent("22/01/2023 20:11:02","[BROS] KiraYamatofreedom (45)","Me (21)","M1 Heavy Cycler"),
			new KillEvent("22/01/2023 20:10:59","Me (21)","[BROS] BariusBackstabius (69)","NS-45 Pilot"),
			new KillEvent("22/01/2023 20:10:16","[RMIS] TobyHD (100)","Me (21)","TAR"),
			new KillEvent("22/01/2023 20:10:01","Me (21)","[WILK] PITERKLM (58)","NS-45 Pilot"),
			new KillEvent("22/01/2023 20:09:57","Me (21)","[RMIS] KrkonosTR (92)","Icikill"),
			new KillEvent("22/01/2023 19:12:11","Me (21)","[91AP] Wehhh (82)","Pandora VX25"),
			new KillEvent("22/01/2023 19:12:08","[GBX] SomeMotivation (17)","Me (21)","NC1 Gauss Rifle"),
			new KillEvent("22/01/2023 19:12:04","Me (21)","[OOPS] zAlakazite (80)","Pandora VX25"),
			new KillEvent("22/01/2023 19:10:55","Me (21)","[ORIG] Neji42 (80)","S12 Renegade(Flash)"),
			new KillEvent("22/01/2023 18:50:51","Me (21)","whatislovich (4)","M12 Kobalt(Sunderer)"),
			new KillEvent("22/01/2023 18:50:50","Me (21)","[EPG] OperDog (89)","M12 Kobalt(Sunderer)"),
			new KillEvent("22/01/2023 18:49:52","[BROS] Mortenjp (51)","Me (21)","TORQ-9"),
			new KillEvent("22/01/2023 18:49:09","[FLAG] Echo049 (98)","Me (21)","MSW-R"),
			new KillEvent("22/01/2023 18:49:00","[EPG] OneShiner (21)","Me (21)","T9 CARV"),
			new KillEvent("22/01/2023 18:49:01","Me (21)","[EPG] lizard6 (22)","Icikill"),
			new KillEvent("22/01/2023 18:49:01","[EPG] lizard6 (22)","Me (21)","TX1 Repeater"),
			new KillEvent("22/01/2023 18:49:12","Me (21)","[BROS] Mortenjp (51)","Pandora VX25"),
			new KillEvent("22/01/2023 18:49:00","DonStar4ez (9)","Me (21)","T1 Cycler"),
			new KillEvent("22/01/2023 18:48:52","TDSweer4 (4)","Me (21)","C-4"),
			new KillEvent("22/01/2023 18:48:44","[CHI] xXTRIPLEHXx (99)","Me (21)","NSX \"Networked\" Naginata"),
			new KillEvent("22/01/2023 18:48:42","Me (21)","[ArcP] Bekimii (67)","VE-H Maw"),
			new KillEvent("22/01/2023 18:48:42","Me (21)","chunliho (11)","Sunderer"),
			new KillEvent("22/01/2023 18:46:00","Me (21)","chunliho (11)","Pandora VX25"),
			new KillEvent("22/01/2023 18:45:58","Me (21)","[PR69] PlumeHo (57)","Pandora VX25"),
			new KillEvent("22/01/2023 18:45:00","[16TD] ZornUndRuhe (55)","Me (21)","MSW-R"),
			new KillEvent("22/01/2023 18:45:01","Me (21)","TDSweer4 (4)","VE-H Maw"),
			new KillEvent("22/01/2023 18:44:00","TDSweer4 (4)","Me (21)","AR-100"),
			new KillEvent("22/01/2023 18:40:00","[EPG] StownSword (8)","Me (21)","T16 Rhino"),
			new KillEvent("22/01/2023 18:40:28","Me (21)","SoftKiller21NSO (66)","Pandora VX25"),
			new KillEvent("22/01/2023 18:42:48","[EPG] StownSword (8)","Me (21)","T16 Rhino"),
			new KillEvent("22/01/2023 18:42:41","Elhos (17)","Me (21)","P2-120 AP(Prowler)"),
			new KillEvent("22/01/2023 18:42:00","Me (21)","[HFGL] Dirdra (92)","Sunderer"),
			new KillEvent("22/01/2023 18:41:47","[975] BasilRomanus (72)","Me (21)","T5 AMC"),
			new KillEvent("22/01/2023 18:41:46","Me (21)","PERSONA01 (14)","VE-H Maw"),
			new KillEvent("22/01/2023 18:41:44","saily2 (99)","Me (21)","Hunter QCX"),
			new KillEvent("22/01/2023 18:05:52","Me (21)","saily2 (99)","M12 Kobalt(Sunderer)"),
			new KillEvent("22/01/2023 18:40:07","chunliho (11)","Me (21)","TRAC-5"),
			new KillEvent("22/01/2023 18:00:48","Me (21)","[DIOR] LerrisTR (100)","H-V45"),
			new KillEvent("22/01/2023 18:00:09","SargerCZech (9)","Me (21)","M77-B"),
			new KillEvent("22/01/2023 18:02:02","[ArcP] netraam (7)","Me (21)","Auraxium Chainblade"),
			new KillEvent("22/01/2023 18:02:22","Me (21)","[BROS] periklesz (98)","H-V45"),
			new KillEvent("22/01/2023 18:02:15","Me (21)","[EPG] lizard6 (22)","H-V45"),
			new KillEvent("22/01/2023 18:02:14","Me (21)","[0M0N] LagyTR (29)","H-V45"),
			new KillEvent("22/01/2023 18:01:47","Me (21)","[ArcP] Bekimii (67)","H-V45"),
			new KillEvent("22/01/2023 18:01:00","Binocula (66)","Me (21)","Rocklet Rifle"),
			new KillEvent("22/01/2023 18:01:18","[ArcP] netraam (7)","Me (21)","SOAS-20"),
			new KillEvent("22/01/2023 18:01:15","Me (21)","FoBoS1111 (44)","H-V45"),
			new KillEvent("22/01/2023 18:29:45","Binocula (66)","Me (21)","U-100 Lastly"),
			new KillEvent("22/01/2023 18:29:42","Me (21)","[EPG] Unitaziks (25)","H-V45"),
			new KillEvent("22/01/2023 18:29:42","Binocula (66)","Me (21)","Rocklet Rifle"),
			new KillEvent("22/01/2023 18:29:41","Me (21)","[FUN] Lundz (9)","H-V45"),
			new KillEvent("22/01/2023 18:28:19","Me (21)","[iSUN] Ravdi (21)","M12 Kobalt(ANT)"),
			new KillEvent("22/01/2023 18:27:42","[prut] JSN2010TR (59)","Me (21)","NS Decimator"),
			new KillEvent("22/01/2023 18:26:41","Me (21)","TDSweer4 (4)","M12 Kobalt(ANT)"),
			new KillEvent("22/01/2023 18:26:09","Me (21)","Liv1a (9)","M12 Kobalt(ANT)"),
			new KillEvent("22/01/2023 18:26:28","Me (21)","[EPG] Seneka1 (68)","M12 Kobalt(ANT)"),
			new KillEvent("22/01/2023 18:26:26","Me (21)","TDSweer4 (4)","M12 Kobalt(ANT)"),
			new KillEvent("22/01/2023 17:08:15","pinceurdeteton (64)","Me (21)","NS-11 \"Endeavor\" Carbine"),
			new KillEvent("22/01/2023 17:06:48","Me (21)","[EPG] Seneka1 (68)","H-V45"),
			new KillEvent("22/01/2023 16:59:45","Me (21)","BeebBeeep (114)","H-V45"),
			new KillEvent("22/01/2023 16:57:40","Me (21)","n/a","H-V45"),
			new KillEvent("22/01/2023 16:51:46","jakeees (99)","Me (21)","Spitfire Auto-Turret(Spitfire Auto-Turret)"),
			new KillEvent("22/01/2023 16:51:29","Me (21)","CharCob (16)","Plasma Grenade"),
			new KillEvent("22/01/2023 16:50:50","Me (21)","[Flu] Painigi (66)","Pandora VX25"),
			new KillEvent("22/01/2023 16:50:20","[BROS] Utaelilya (6)","Me (21)","NS-66 Punisher"),
			new KillEvent("22/01/2023 16:49:52","XlopezX (7)","Me (21)","M20 Basilisk(Sunderer)"),
			new KillEvent("22/01/2023 16:49:51","Me (21)","sivyy (9)","Pandora VX25"),
			new KillEvent("22/01/2023 16:49:50","Me (21)","MonkyRoboStupit (71)","Pandora VX25"),
			new KillEvent("22/01/2023 16:49:00","Me (21)","VODKAVODKAVODKA (22)","Pandora VX25"),
			new KillEvent("22/01/2023 16:49:05","sharkhhNSO (72)","Me (21)","L100 Python HESH(Lightning)"),
			new KillEvent("22/01/2023 16:47:07","[ArcP] Bekimii (67)","Me (21)","NS-45 Pilot"),
			new KillEvent("22/01/2023 16:47:05","Me (21)","[TTRO] Herubrand (40)","C-4 ARX"),
			new KillEvent("22/01/2023 16:47:05","Me (21)","[BROS] Utaelilya (6)","C-4 ARX"),
			new KillEvent("22/01/2023 16:46:48","[TTRO] CrowShot (87)","Me (21)","L100 Python HESH(Lightning)"),
			new KillEvent("22/01/2023 16:45:46","Me (21)","roboticimpulse (51)","Pandora VX25"),
			new KillEvent("22/01/2023 16:45:07","Me (21)","[P0R] spinshot46 (66)","NS-66 Punisher"),
			new KillEvent("22/01/2023 16:44:54","[ALXS] 0OEleven (27)","Me (21)","XMG-100"),
			new KillEvent("22/01/2023 16:44:05","Me (21)","[GRDD] RememberMattie (6)","Icikill"),
			new KillEvent("22/01/2023 16:44:21","Me (21)","[91AR] Woodythree (52)","Pandora VX25"),
			new KillEvent("22/01/2023 16:44:21","[418] Kenshini (60)","Me (21)","GD-22S"),
			new KillEvent("22/01/2023 16:44:16","Me (21)","[ALXS] xiaomeng2 (41)","Pandora VX25"),
			new KillEvent("22/01/2023 16:40:58","[CBMC] edgardeutschland (61)","Me (21)","VE-C Horizon"),
			new KillEvent("22/01/2023 16:40:57","Me (21)","[RE4] Atlan0815 (100)","Pandora VX25"),
			new KillEvent("22/01/2023 16:42:08","[W1] SerWOLF (99)","Me (21)","NS-15MB"),
			new KillEvent("22/01/2023 16:42:01","Me (21)","[DJOP] BlazingMissile (120)","Pandora VX25"),
			new KillEvent("22/01/2023 16:41:20","Me (21)","[91AR] SGTAngryAcorn (9)","Pandora VX25"),
			new KillEvent("22/01/2023 16:39:55","[GRDD] RememberMattie (6)","Me (21)","NS-44 Commissioner"),
			new KillEvent("22/01/2023 16:39:01","Sigismund8642 (1)","Me (21)","M1 Heavy Cycler"),
			new KillEvent("22/01/2023 16:39:00","Me (21)","CharCob (16)","NS-45 Pilot"),
			new KillEvent("22/01/2023 16:38:10","xxxAGENTxxx (67)","Me (21)","XMG-155"),
			new KillEvent("22/01/2023 16:38:16","Me (21)","Derhed (1)","NS-45 Pilot"),
			new KillEvent("22/01/2023 16:38:10","Me (21)","LynX161 (10)","Icikill"),
			new KillEvent("22/01/2023 16:37:42","[HTOO] Garuda25 (91)","Me (21)","M77-B"),
			new KillEvent("22/01/2023 16:35:09","Me (21)","[PR69] PlumeHo (57)","NS-66 Punisher")
		};
}
